[project]
name = "check-missing-send"
version = "0.1.0"
description = "Temperature monitoring dashboard"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dash",
    "flask",
    "gunicorn",
    "plotly",
    "beautifulsoup4",
    "requests",
    "pandas",
]

#[build-system]
#requires = ["hatchling"]
#build-backend = "hatchling.build"
